services:
  news-retrieval:
    image: "heussd/news-retrieval"
    build: .
    volumes:
      - "${PWD}/data:/data/"
    environment: 
      - FIVE_FILTERS_SERVICE=fullfeedrss
    command:
      - "/data/urls"
      - "/data/sql.db"
  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss"
