version: "3.7"
services:
  news-retrieval:
    image: "heussd/news-retrieval"
    build: .
    privileged: true # Required for sleep(!) on ARM Linux (?!)
    volumes:
      - "${PWD}/data:/data/"
    environment: 
      - FIVE_FILTERS_SERVICE=fullfeedrss
    command:
      - "/data/urls"
      - "/data/sql.db"
  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss"
